variables:
  IMAGE_TAG: nishantgaikwad9665/python:$CI_COMMIT_SHORT_SHA

build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "nishantgaikwad9665" --password-stdin
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG