stages:
  - trigger

trigger_stack_pipeline:
  stage: trigger
  trigger:
    include:
      - project: 'kone2554021/shared-cicd-pipeline'
        ref: main
        file: "ci-templates/${STACK}-template.yml"
    strategy: depend
    forward:
      pipeline_variables: true
